### PR TITLE
Pass in activeLesson

### PR DESCRIPTION
**Pull request by brylie**

### CODE REVIEW

**Comment by brylie** [comment]
@Crowducate/development please review. This fixes #109

**Comment by brylie** [comment]
@Crowducate/development any progress on reviewing this PR?

**Comment by sebbel** [comment]
i have problems to even get there with the current code of develop, which I mentioned in #109. I will write a bug shortly

**Comment by Rahbaran** [comment]
Same here. Reasons are mentioned in #109

**Comment by sebbel** [comment]
cannot test because of #113, which is happening on this branch as well

**Comment by brylie** [comment]
Closing this as it is included in PR #114

**Pull request closed without merging**
