### PR TITLE
Meteor update.

### PR DESCRIPTION
**Pull request by brylie**
Basic update to community packages. No API breaking changes.

### CODE REVIEW

**Comment by brylie** [comment]
@Crowducate/development please review and merge ASAP.

**Comment by sebbel** [comment]
[Learn]-Tab yields no results. Even after creation of new courses.
Can someone reproduce?

**Comment by Rahbaran** [comment]
@brylie @sbe : I could reproduce it. Switching the branch to 'develop' shows the learn tab again.

**Comment by sebbel** [comment]
must be one of the collection packages, I'll try to narrow it down

**Comment by sebbel** [comment]
Getting an error in the console: You now need a routing package like useraccounts:iron-routing or useraccounts:flow-routing to be able to configure routes!

Guess we need that package and configure the routes again.

**Comment by brylie** [comment]
I have opened an issue #104 regarding the blank learn page, with an accompanying pull request.

Regarding this pull request, I have added the missing package, updated all remaining packages, and tested it to work locally. 

@Crowducate/development  please review.

**Comment by sebbel** [comment]
Thank you, Brylie! It's working again.

**Pull request merged**
