### PR TITLE
Add publishedCourses subscription

### PR DESCRIPTION
**Pull request by brylie**
Template level subscription to resolve issue #104

### CODE REVIEW

**Comment by brylie** [comment]
@Crowducate/development please review.

**Comment by brylie** [comment]
I manually merged this one, as it had conflicts and I am fixing another bug.

**Comment by brylie** [comment]
@Crowducate/development please review the [changes](https://github.com/Crowducate/crowducate-platform/pull/105/files) anyway, so that we can have multiple eyes on the code changes.

**Comment by sebbel** [comment]
okay, I was about to merge it from here. Good to know! :+1:

**Comment by sebbel** [comment]
I did review the changes. Learn page is not empty anymore. Logged in and created a course, which appeared instantly.

**Pull request merged**
